{
  "modified": "2024-10-16T14:43:40Z",
  "published": "2024-10-16T14:43:40Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5363"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "microauth2"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/microauth2/MAL-2024-5363.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "01b92f789987b96dba94c12d97978c744606d2a5b0450c91dffe9d349c13e68e",
        "import_time": "2024-10-24T00:59:27.375858298Z",
        "id": "RLUA-2024-08514",
        "modified_time": "2024-10-16T14:43:40Z"
      }
    ]
  }
}
