{
  "modified": "2024-10-16T14:46:37Z",
  "published": "2024-10-16T14:46:37Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5588"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-coad"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-coad/MAL-2024-5588.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "058950130b2fe83d83bfd9d63881dd5fb7cfbceba6261d639410832704d0a441",
        "import_time": "2024-10-24T00:59:42.70567611Z",
        "id": "RLUA-2024-08803",
        "modified_time": "2024-10-16T14:46:37Z"
      }
    ]
  }
}
