{
  "modified": "2024-10-16T14:39:22Z",
  "published": "2024-10-16T14:39:22Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5028"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "data-platform-dbt"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/data-platform-dbt/MAL-2024-5028.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "70db379d85742faa5d4e577233bf5cb8207b92e1a3721593f0a16b519e2c9216",
        "import_time": "2024-10-24T00:59:04.652769095Z",
        "id": "RLUA-2024-08104",
        "modified_time": "2024-10-16T14:39:22Z"
      }
    ]
  }
}
