{
  "modified": "2024-10-16T14:48:04Z",
  "published": "2024-10-16T14:48:04Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5719"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pyheul"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyheul/MAL-2024-5719.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "5e1376b8836c97f6c29f911530d54c13b8e9d84309ed842f4da77641b3f4485d",
        "import_time": "2024-10-24T00:59:52.038880395Z",
        "id": "RLUA-2024-08941",
        "modified_time": "2024-10-16T14:48:04Z"
      }
    ]
  }
}
