{
  "modified": "2025-03-03T13:45:12Z",
  "published": "2025-03-03T13:45:12Z",
  "schema_version": "1.5.0",
  "id": "",
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "ransomware",
        "purl": "pkg:pypi/ransomware"
      },
      "versions": [
        "1.0.0"
      ]
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "3a0588fb5593464ad7203344644a0e171f285ddfca658dd4d39cf29858df2827",
        "import_time": "2025-03-03T15:07:16.5929093Z",
        "id": "RLMA-2025-01231",
        "modified_time": "2025-03-03T13:45:12Z",
        "versions": [
          "1.0.0"
        ]
      }
    ]
  }
}
