{
  "modified": "2024-10-16T14:43:42Z",
  "published": "2024-10-16T14:43:42Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5366"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "milleday"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/milleday/MAL-2024-5366.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "fb3e3cc143602f7adfdc5fbe0766398bcd23348af40a088687f37beac68d26fa",
        "import_time": "2024-10-24T00:59:27.544369423Z",
        "id": "RLUA-2024-08517",
        "modified_time": "2024-10-16T14:43:42Z"
      }
    ]
  }
}
