{
  "modified": "2024-10-16T14:48:28Z",
  "published": "2024-10-16T14:48:28Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5756"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pypackagehelp"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pypackagehelp/MAL-2024-5756.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "873373daa81615ebaf86d11365b20dc27d8b32d326bf9f8e980d81e894fd90f4",
        "import_time": "2024-10-24T00:59:54.34411512Z",
        "id": "RLUA-2024-08981",
        "modified_time": "2024-10-16T14:48:28Z"
      }
    ]
  }
}
