{
  "modified": "2024-10-16T14:50:09Z",
  "published": "2024-10-16T14:50:09Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5887"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "request9"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/request9/MAL-2024-5887.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "71441e022d16cd53e65652ddfde972abd61ea05a10d2645d15e4eaf359ab7bc0",
        "import_time": "2024-10-24T01:00:03.220644709Z",
        "id": "RLUA-2024-09147",
        "modified_time": "2024-10-16T14:50:09Z"
      }
    ]
  }
}
