{
  "modified": "2024-10-16T14:48:08Z",
  "published": "2024-10-16T14:48:08Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5724"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pyinitise"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pyinitise/MAL-2024-5724.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "2db11f113de444c219241fe05b497360e228aaf7a0f85f824aa5e149d1e9f7f1",
        "import_time": "2024-10-24T00:59:52.398486476Z",
        "id": "RLUA-2024-08948",
        "modified_time": "2024-10-16T14:48:08Z"
      }
    ]
  }
}
