{
  "modified": "2024-10-16T14:45:48Z",
  "published": "2024-10-16T14:45:48Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5513"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pipcryptoaddonv1"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pipcryptoaddonv1/MAL-2024-5513.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "d1405f96eea97db8c4038583987d931fc4dceb69c27f2c32f96a967ceabf199e",
        "import_time": "2024-10-24T00:59:37.702639741Z",
        "id": "RLUA-2024-08723",
        "modified_time": "2024-10-16T14:45:48Z"
      }
    ]
  }
}
