{
  "modified": "2024-10-16T14:39:55Z",
  "published": "2024-10-16T14:39:55Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5080"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "discordpy-v3"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/discordpy-v3/MAL-2024-5080.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "bdfc5a620feaddfd650cea293ecc4c02bb722c9f7cfb14672ece331053cfa9a6",
        "import_time": "2024-10-24T00:59:08.025109027Z",
        "id": "RLUA-2024-08157",
        "modified_time": "2024-10-16T14:39:55Z"
      }
    ]
  }
}
