{
  "modified": "2024-10-16T14:52:30Z",
  "published": "2024-10-16T14:52:30Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-6107"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "test-package-main-dist"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/test-package-main-dist/MAL-2024-6107.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "5795ce22f19662a3e250ad0172a39208ca56349fd489fe2524e06355a83ddc80",
        "import_time": "2024-10-24T01:00:18.268710622Z",
        "id": "RLUA-2024-09378",
        "modified_time": "2024-10-16T14:52:30Z"
      }
    ]
  }
}
