{
  "modified": "2024-10-16T14:49:18Z",
  "published": "2024-10-16T14:49:18Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5827"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "pythonsqlitepkgsv2"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/pythonsqlitepkgsv2/MAL-2024-5827.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "a96b55c484644b40cd8271fc5781beca6f87dc9405f298500af036b14dacbdaf",
        "import_time": "2024-10-24T00:59:59.031892498Z",
        "id": "RLUA-2024-09066",
        "modified_time": "2024-10-16T14:49:18Z"
      }
    ]
  }
}
