{
  "modified": "2024-10-16T14:44:26Z",
  "published": "2024-10-16T14:44:26Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5432"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "od7n"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/od7n/MAL-2024-5432.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "79e566960411006dcdc679d3dc4b9d1e67355bc3caf8637a57ec5d15801e6e23",
        "import_time": "2024-10-24T00:59:32.20674714Z",
        "id": "RLUA-2024-08588",
        "modified_time": "2024-10-16T14:44:26Z"
      }
    ]
  }
}
