{
  "modified": "2024-06-25T13:32:28Z",
  "published": "2024-06-25T13:32:28Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "SNYK-PYTHON-ARGSPYTHON-5591088"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "args-python",
        "purl": "pkg:pypi/args-python"
      },
      "versions": [
        "12.4.5",
        "12.5.5"
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://security.snyk.io/vuln/SNYK-PYTHON-ARGSPYTHON-5591088"
    },
    {
      "type": "ARTICLE",
      "url": "https://medium.com/checkmarx-security/pypi-on-hold-suspends-new-users-and-projects-creations-due-to-a-high-volume-of-malicious-activity-7ff09cd25f3e"
    }
  ],
  "credits": [
    {
      "name": "ReversingLabs",
      "type": "FINDER",
      "contact": [
        "https://www.reversinglabs.com"
      ]
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "98e3c2618a36d29a675de35b1d681d843c7eb7aa6afaeca5d09e62c9b290729a",
        "import_time": "2024-06-28T02:48:17.065670703Z",
        "id": "RLMA-2024-03555",
        "modified_time": "2024-06-25T13:32:28Z",
        "versions": [
          "12.4.5",
          "12.5.5"
        ]
      }
    ]
  }
}
