{
  "modified": "2024-10-16T14:47:03Z",
  "published": "2024-10-16T14:47:03Z",
  "schema_version": "1.5.0",
  "id": "",
  "aliases": [
    "MAL-2024-5630"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "PyPI",
        "name": "py-cyrd"
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/ossf/malicious-packages/blob/main/osv/malicious/pypi/py-cyrd/MAL-2024-5630.json"
    }
  ],
  "database_specific": {
    "malicious-packages-origins": [
      {
        "source": "reversing-labs",
        "sha256": "d5a588beef9f05245969f550981c0da08febfceb12727b50b529155220e76c9a",
        "import_time": "2024-10-24T00:59:45.659292622Z",
        "id": "RLUA-2024-08845",
        "modified_time": "2024-10-16T14:47:03Z"
      }
    ]
  }
}
